web/router.ex
defmodule Seblog.Router do
  use Seblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Seblog.Plug.TemplateTheme, %{theme: "default"}
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: Seblog.Token
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", Seblog do
    pipe_through [:api]
    post "/admin/posts/ifttt", PostController, :ifttt
    get "/admin/images/pallette", ImageController, :pallette
    get "/admin/images/pallette/:name", ImageController, :pallette
  end

  scope "/admin", Seblog do
    pipe_through [:browser, :browser_auth]
    post "/posts/:id/publish", PostController, :publish
    resources "/posts", PostController
    resources "/tags", TagController
    resources "/images", ImageController
    resources "/themes", ThemeController
    get "/", SessionController, :check_login
    get "/login", SessionController, :check_login
    get "/logout", SessionController, :delete
  end

  scope "/", Seblog do
    pipe_through [:browser, :browser_auth]
    get "/:year/:date/:slug/write", PostController, :edit_inline
    get "/write", PostController, :new_inline
  end

  scope "/", Seblog do
    pipe_through :browser # Use the default browser stack
    resources "/admin/sessions", SessionController, only: [:new, :create, :delete]
    resources "/admin/admins", AdminController
    get "/page/:page", PageController, :by_page
    get "/", PageController, :index
    get "/approve-draft/:id/:key", PostController, :quick_approve_draft
    get "/:year/:date/:slug", PageController, :show
  end



  # Other scopes may use custom stacks.
  # scope "/api", Seblog do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Seblog.LayoutView do
  use Seblog.Web, :view
end

web/templates/default/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= site_name(@conn) %> - <%= site_title(@conn) %></title>
    <meta id="viewport" name="viewport" content ="width=device-width, initial-scale=1.0, overflow:hidden, user-scalable=no" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <%= render_existing view_module(@conn), "styles.html", assigns %>
    <style>

      body {
          max-width: 900px;
          font: 18px/1.4 'Open Sans', sans-serif;
          color: #555;
          background-color: #eee;
      }

      a {
          display: inline-block;
          padding: 10px 20px;
          color: #fff;
          text-decoration: none;
      }

      .excerpt img, .excerpt iframe {
        display: none;
      }

      section {
          margin-top: 60px;
      }

      textarea {
          width: 80%;
          height: 32em;
          padding: 20px;
          color: #555;
          font: 18px/25px 'Roboto Mono', sans-serif;
      }

      /*script {
          display: block;
          margin-top: 10px;
          padding-left: 10px;
          border-left: 8px solid #ccc;
          white-space: pre-wrap;
          font: 14px/1.4 'Roboto Mono', sans-serif;
      }*/

      h1,h2,h3 {
          line-height:1.2;
      }
    </style>
    </head>

    <body>
    <div class="container">
    <header class="header">
    <nav role="navigation">
      <ul class="nav nav-pills pull-right">
        <%= render "sign_in_sign_out.html", conn: @conn %><br><br>
      </ul>
    </nav>
    </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

        <%= render @view_module, @view_template, assigns %>

    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <%= render_existing view_module(@conn), "scripts.html", assigns %>
    </body>
</html>

web/templates/default/layout/editor.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render_existing view_module(@conn), "meta.html", assigns %>
    <title><%= assigns[:page_title] || site_name(@conn) %> <%= site_title(@conn) %></title>
    <meta id="viewport" name="viewport" content ="width=device-width, initial-scale=1.0, overflow:hidden, user-scalable=no" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/public.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/editor.css") %>">
  </head>

  <body>
    <nav class="demo">
      <%# <h1>Seb Potter</h1> %>
      <a href="/" class="brand">
        <img class="logo" src="<%= static_path(@conn, "/images/seblogo.png") %>" />
        <span>From the mind of Seb</span>
      </a>

      <!-- responsive-->
      <input id="bmenub" type="checkbox" class="show">
      <label for="bmenub" class="burger pseudo button">menu</label>

      <div class="menu">
        <%= if logged_in?(@conn) do %><%= if @post.status != "publish" do %><button id="publish-button" class="button small">Publish?</button><% end %><% else %>
        <a href="https://www.linkedin.com/in/sebpotter" class="pseudo button icon-globe">Profile</a>
        <a href="https://github.com/iamseb/seblog" target="_blank" class="pseudo button icon-g">Github</a>
        <% end %>
      </div>
    </nav>
    <main>
      <div class="flex one three-800">
          <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <script src="<%= static_path(@conn, "/js/editor.js") %>"></script>
    <%= render_existing view_module(@conn), "scripts.html", assigns %>
    <script type="text/javascript">
      $(document).ready(function(){
        $("img[data-fullsize]").each(function(){
          var imgLarge = new Image();
          imgLarge.src = $(this).data("fullsize");
          var outer_image = $(this);
          imgLarge.onload = function(){
            outer_image.wrap("<div class=\"progressive-container\"></div>");
            outer_image.parent().css("background", "url("+ outer_image.data("fullsize") + ")");
            outer_image.animate({opacity: 0}, 2000);
          }
        });
        var loc = window.location.host;
        $('a[href^=http]:not([href*="' + loc + '"])')
          .attr('target','_blank');
      });

    </script>
    <%= if google_analytics(@conn) != "" do %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= google_analytics(@conn) %>', 'auto');
      ga('send', 'pageview');

    </script>
    <% end %>
  </body>
</html>

web/templates/default/layout/public.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render_existing view_module(@conn), "meta.html", assigns %>
    <title><%= assigns[:page_title] || site_name(@conn) %> <%= site_title(@conn) %></title>
    <meta id="viewport" name="viewport" content ="width=device-width, initial-scale=1.0, overflow:hidden, user-scalable=no" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/public.css") %>">
  </head>

  <body>
    <nav class="demo">
      <%# <h1>Seb Potter</h1> %>
      <a href="/" class="brand">
        <img class="logo" src="<%= static_path(@conn, "/images/seblogo.png") %>" />
        <span>From the mind of Seb</span>
      </a>

      <!-- responsive-->
      <input id="bmenub" type="checkbox" class="show">
      <label for="bmenub" class="burger pseudo button">menu</label>

      <div class="menu">
        <%= if logged_in?(@conn) do %>Hello <%= current_admin(@conn).name %>,
        <a href="<%= post_path(@conn, :new_inline)%>">Write a story</a><% else %>
        <a href="https://www.linkedin.com/in/sebpotter" class="pseudo button icon-globe">Profile</a>
        <a href="https://github.com/iamseb/seblog" target="_blank" class="pseudo button icon-g">Github</a>
        <% end %>
      </div>
    </nav>
    <main>
      <div class="flex one three-800">
          <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <script src="<%= static_path(@conn, "/js/public.js") %>"></script>
    <%= render_existing view_module(@conn), "scripts.html", assigns %>
    <script type="text/javascript">
      $(document).ready(function(){
        $("img[data-fullsize]").each(function(){
          var imgLarge = new Image();
          imgLarge.src = $(this).data("fullsize");
          var outer_image = $(this);
          imgLarge.onload = function(){
            outer_image.wrap("<div class=\"progressive-container\"></div>");
            outer_image.parent().css("background", "url("+ outer_image.data("fullsize") + ")");
            outer_image.animate({opacity: 0}, 2000);
          }
        });
        var loc = window.location.host;
        $('a[href^=http]:not([href*="' + loc + '"])')
          .attr('target','_blank');
      });

    </script>
    <%= if google_analytics(@conn) != "" do %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= google_analytics(@conn) %>', 'auto');
      ga('send', 'pageview');

    </script>
    <% end %>
  </body>
</html>

web/templates/default/layout/sign_in_sign_out.html.eex
<%= if logged_in?(@conn) do %>
  <%= link "Sign out", to: session_path(@conn, :delete),
      method: :delete, class: "btn btn-danger" %><br>
  <%= current_admin(@conn).email %>
<% else %>
  <%= link "Create new account", to: admin_path(@conn, :new),
      class: "btn btn-danger" %>
  <%= link "Sign in", to: session_path(@conn, :new),
      class: "btn btn-danger" %>
<% end %>